version: '3.8'
services:
  backend:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
        - "80:80"
    command: npm run start-dev
    env_file:
      - ./.env.development

